//import Head from "next/head";
import Homepage from "@/Components/Homepage";

export default function Home(props) {
  return <Homepage />;
}

//  <Head>
//         <title>Create Next Application</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={"star"}>
//         <h1>Manin content</h1>
//       </main>
